export default {
    pages: {
        home: {
            tabName: {
                ru: 'Главная',
                ua: 'Головна',
                en: 'Home',
                de: 'Hauptseite',
                pl: 'Główna',
            },
            title: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            titleBattle: {
                ru: 'Боевой',
                ua: 'Бойовий',
                en: 'Battle',
                de: 'Battle',
                pl: 'Bojowy',
            },
            titlePass: {
                ru: 'Пропуск',
                ua: 'Пропуск',
                en: 'Pass',
                de: 'Pass',
                pl: 'Karnet',
            },
            description: {
                ru: 'Встречайте наш первый боевой пропуск!\nВыполняйте задания и получайте уникальные награды.',
                ua: 'Зустрічайте наш перший бойовий пропуск!\nВиконуйте завдання та отримуйте унікальні нагороди.',
                en: 'Meet our very first battle pass!\nComplete quests and earn unique rewards.',
                de: 'Lernt unseren ersten Battle Pass kennen!\nErfüllt Aufgaben und erhaltet einzigartige Belohnungen.',
                pl: 'Poznajcie naszą pierwszą przepustkę bojową!\nWykonuj zadania i zdobywaj wyjątkowe nagrody.',
            },
        },
        upgrade: {
            tabName: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            title: {
                ru: 'Улучшение пропуска',
                ua: 'Покращення пропуску',
                en: 'Pass upgrade',
                de: 'Pass-Upgrade',
                pl: 'Ulepszenie przepustki',
            },
            description: {
                ru: 'Откройте полный потенциал пропуска!\nВыбирайте свой тир и забирайте эксклюзивные премиум-награды.',
                ua: 'Розкрийте повний потенціал пропуску!\nОбирайте свій тир і забирайте ексклюзивні преміум-нагороди.',
                en: 'Unlock the full potential of your pass!\nChoose your tier and claim exclusive premium rewards.',
                de: 'Entfaltet das volle Potenzial des Passes!\nWähle deine Stufe und sichere dir exklusive Premium-Belohnungen.',
                pl: 'Odkryj pełny potencjał przepustki!\nWybierz swój poziom i zgarnij ekskluzywne nagrody premium.',
            },
            passWord: {
                ru: 'пропуск',
                ua: 'пропуск',
                en: 'pass',
                de: 'Pass',
                pl: 'przepustka',
            },
            starterDescription: {
                ru: 'Вам доступны награды только в верхней ленте. Улучшите пропуск чтобы получить более ценные награды.',
                ua: 'Вам доступні нагороди лише у верхній стрічці. Покращте пропуск, щоб отримати більш цінні нагороди.',
                en: 'You only get rewards from the top track. Upgrade the pass to unlock more valuable rewards.',
                de: 'Du erhältst nur Belohnungen aus der oberen Spur. Verbessere den Pass, um wertvollere Belohnungen freizuschalten.',
                pl: 'Otrzymujesz nagrody tylko z górnego toru. Ulepsz przepustkę, aby odblokować cenniejsze nagrody.',
            },
            unlockTo: {
                ru: 'Открывает доступ к',
                ua: 'Відкриває доступ до',
                en: 'Unlocks access to',
                de: 'Schaltet den Zugang frei zu',
                pl: 'Odblokowuje dostęp do',
            },
            unlockRange: {
                ru: '1-{{max}} Премиум уровням',
                ua: '1-{{max}} Преміум рівням',
                en: '1-{{max}} Premium levels',
                de: '1-{{max}} Premium-Level',
                pl: '1-{{max}} poziomów Premium',
            },
            refreshPrefix: {
                ru: 'Смена заданий раз в',
                ua: 'Зміна завдань раз на',
                en: 'Tasks refresh every',
                de: 'Aufgaben werden alle',
                pl: 'Zmiana zadań co',
            },
            refreshValue: {
                ru: '{{hours}} часов',
                ua: '{{hours}} годин',
                en: '{{hours}} hours',
                de: '{{hours}} Stunden',
                pl: '{{hours}} godzin',
            },
            startFree: {
                ru: 'Начать бесплатно',
                ua: 'Почати безкоштовно',
                en: 'Start for free',
                de: 'Kostenlos starten',
                pl: 'Zacznij za darmo',
            },
            buy: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            active: {
                ru: 'Активно',
                ua: 'Активно',
                en: 'Active',
                de: 'Aktiv',
                pl: 'Aktywne',
            },
            level: {
                ru: 'Уровень {{level}}',
                ua: 'Рівень {{level}}',
                en: 'Level {{level}}',
                de: 'Level {{level}}',
                pl: 'Poziom {{level}}',
            },
            noShowcase: {
                ru: 'Скоро здесь появятся награды',
                ua: 'Скоро тут з’являться нагороди',
                en: 'Rewards coming soon',
                de: 'Bald gibt es hier Belohnungen',
                pl: 'Wkrótce pojawią się nagrody',
            },
            confirmModalTitle: {
                ru: 'Подтверждение покупки пропуска',
                ua: 'Підтвердження купівлі пропуску',
                en: 'Confirm pass purchase',
                de: 'Pass-Kauf bestätigen',
                pl: 'Potwierdzenie zakupu przepustki',
            },
            confirmButton: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancelButton: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
            modalBody: {
                buy: {
                    ru: 'Купить',
                    ua: 'Купити',
                    en: 'Buy',
                    de: 'Kaufen',
                    pl: 'Kup',
                },
                for: {
                    ru: 'за',
                    ua: 'за',
                    en: 'for',
                    de: 'für',
                    pl: 'za',
                },
            },
        },
        buyXp: {
            tabName: {
                ru: 'Купить опыт',
                ua: 'Купити досвід',
                en: 'Buy XP',
                de: 'XP kaufen',
                pl: 'Kup XP',
            },
            title: {
                ru: 'Покупка опыта',
                ua: 'Купівля досвіду',
                en: 'Buy experience',
                de: 'Erfahrung kaufen',
                pl: 'Kupowanie doświadczenia',
            },
            description: {
                ru: 'Не хватает времени, но хочется наград?\nКупите опыт пропуска и быстро доберитесь до нужных уровней.',
                ua: 'Не вистачає часу, але хочеться нагород?\nКупіть досвід пропуску й швидко дістаньтеся потрібних рівнів.',
                en: 'Short on time but want the rewards?\nBuy battle pass XP and quickly reach the levels you need.',
                de: 'Wenig Zeit, aber Lust auf Belohnungen?\nKaufe Pass-Erfahrung und erreiche schnell die gewünschten Level.',
                pl: 'Brakuje czasu, a chcesz nagród?\nKup doświadczenie przepustki i szybko dotrzyj do potrzebnych poziomów.',
            },
            maxLevelTitle: {
                ru: 'Купить до {{level}} уровня',
                ua: 'Купити до {{level}} рівня',
                en: 'Buy up to level {{level}}',
                de: 'Bis Level {{level}} kaufen',
                pl: 'Kup do poziomu {{level}}',
            },
            maxLevelDescription: {
                ru: 'Это самое простое и выгодное решение купить все недостающие уровни боевого пропуска',
                ua: 'Це найпростіше і найвигідніше рішення купити всі відсутні рівні бойового пропуску',
                en: 'The simplest and best value way to buy every missing battle pass level',
                de: 'Der einfachste und günstigste Weg, alle fehlenden Battle-Pass-Level zu kaufen',
                pl: 'Najprostszy i najbardziej opłacalny sposób na zakup wszystkich brakujących poziomów karnetu bojowego',
            },
            modalTitle: {
                ru: 'EXP для Боевого Пропуска {{year}}',
                ua: 'EXP для Бойового Пропуску {{year}}',
                en: 'EXP for Battle Pass {{year}}',
                de: 'EXP für Battle Pass {{year}}',
                pl: 'EXP do Karnetu Bojowego {{year}}',
            },
            modalBody: {
                buy: {
                    ru: 'Купить',
                    ua: 'Купити',
                    en: 'Buy',
                    de: 'Kaufen',
                    pl: 'Kup',
                },
                for: {
                    ru: 'за',
                    ua: 'за',
                    en: 'for',
                    de: 'für',
                    pl: 'za',
                },
            },
            confirmButton: {
                ru: 'Купить',
                ua: 'Купити',
                en: 'Buy',
                de: 'Kaufen',
                pl: 'Kup',
            },
            cancelButton: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
        },
        quests: {
            tabName: {
                ru: 'Задания',
                ua: 'Завдання',
                en: 'Quests',
                de: 'Aufträge',
                pl: 'Zadania',
            },
            title: {
                ru: 'Задания пропуска',
                ua: 'Завдання пропуску',
                en: 'Pass quests',
                de: 'Pass-Aufgaben',
                pl: 'Zadania przepustki',
            },
            description: {
                ru: 'Ваш список целей на сегодня.\nВыполняйте задания и зарабатывайте опыт пропуска.',
                ua: 'Ваш список цілей на сьогодні.\nВиконуйте завдання та заробляйте досвід пропуску.',
                en: 'Your goals for today.\nComplete quests and earn battle pass experience.',
                de: 'Deine Ziele für heute.\nErfülle Aufgaben und verdiene Pass-Erfahrung.',
                pl: 'Twoja lista celów na dziś.\nWykonuj zadania i zdobywaj doświadczenie przepustki.',
            },
            refreshIn: {
                ru: 'До обновления списка заданий',
                ua: 'До оновлення списку завдань',
                en: 'Until task list refresh',
                de: 'Bis zur Aktualisierung der Aufgabenliste',
                pl: 'Do odświeżenia listy zadań',
            },
            refreshNow: {
                ru: 'Обновить сейчас',
                ua: 'Оновити зараз',
                en: 'Refresh now',
                de: 'Jetzt aktualisieren',
                pl: 'Odśwież teraz',
            },
            refreshConfirmModalTitle: {
                ru: 'Подтверждение обновления заданий',
                ua: 'Підтвердження оновлення завдань',
                en: 'Confirm task refresh',
                de: 'Aufgabenaktualisierung bestätigen',
                pl: 'Potwierdzenie odświeżenia zadań',
            },
            refreshConfirmButton: {
                ru: 'Обновить',
                ua: 'Оновити',
                en: 'Refresh',
                de: 'Aktualisieren',
                pl: 'Odśwież',
            },
            refreshCancelButton: {
                ru: 'Отмена',
                ua: 'Скасувати',
                en: 'Cancel',
                de: 'Abbrechen',
                pl: 'Anuluj',
            },
            refreshModalBody: {
                refresh: {
                    ru: 'Обновить',
                    ua: 'Оновити',
                    en: 'Refresh',
                    de: 'Aktualisieren',
                    pl: 'Odśwież',
                },
                allTasks: {
                    ru: 'все задания',
                    ua: 'всі завдання',
                    en: 'all tasks',
                    de: 'alle Aufgaben',
                    pl: 'wszystkie zadania',
                },
                for: {
                    ru: 'за',
                    ua: 'за',
                    en: 'for',
                    de: 'für',
                    pl: 'za',
                },
            },
            reward: {
                ru: 'Награда',
                ua: 'Нагорода',
                en: 'Reward',
                de: 'Belohnung',
                pl: 'Nagroda',
            },
            replace: {
                ru: 'Заменить',
                ua: 'Замінити',
                en: 'Replace',
                de: 'Ersetzen',
                pl: 'Zamień',
            },
            track: {
                ru: 'Отслеживать',
                ua: 'Відстежувати',
                en: 'Track',
                de: 'Verfolgen',
                pl: 'Śledź',
            },
            untrack: {
                ru: 'Не отслеживать',
                ua: 'Не відстежувати',
                en: 'Untrack',
                de: 'Nicht verfolgen',
                pl: 'Nie śledź',
            },
            jobs: {
                delivery: {
                    title: {
                        ru: 'Время доставки',
                        ua: 'Час доставки',
                        en: 'Delivery time',
                        de: 'Lieferzeit',
                        pl: 'Czas dostawy',
                    },
                    description: {
                        ru: 'Выполните {{target}} заказов на работе доставщика еды.',
                        ua: 'Виконайте {{target}} замовлень на роботі доставника їжі.',
                        en: 'Complete {{target}} orders as a food delivery courier.',
                        de: 'Erfülle {{target}} Bestellungen als Essenslieferant.',
                        pl: 'Wykonaj {{target}} zamówień jako dostawca jedzenia.',
                    },
                },
                diving: {
                    title: {
                        ru: 'Морские глубины',
                        ua: 'Морські глибини',
                        en: 'Deep waters',
                        de: 'Meerestiefen',
                        pl: 'Morskie głębiny',
                    },
                    description: {
                        ru: 'Соберите {{target}} предметов на работе дайвером.',
                        ua: 'Зберіть {{target}} предметів на роботі дайвером.',
                        en: 'Collect {{target}} items while working as a diver.',
                        de: 'Sammle {{target}} Gegenstände als Taucher.',
                        pl: 'Zbierz {{target}} przedmiotów pracując jako nurek.',
                    },
                },
                mushrooms: {
                    title: {
                        ru: 'Грибной сбор',
                        ua: 'Грибний збір',
                        en: 'Mushroom picking',
                        de: 'Pilze sammeln',
                        pl: 'Zbieranie grzybów',
                    },
                    description: {
                        ru: 'Соберите {{target}} грибов на работе сборщика.',
                        ua: 'Зберіть {{target}} грибів на роботі збирача.',
                        en: 'Pick {{target}} mushrooms while working as a forager.',
                        de: 'Sammle {{target}} Pilze als Sammler.',
                        pl: 'Zbierz {{target}} grzybów pracując jako zbieracz.',
                    },
                },
                treasure: {
                    title: {
                        ru: 'Охотник за сокровищами',
                        ua: 'Мисливець за скарбами',
                        en: 'Treasure hunter',
                        de: 'Schatzsucher',
                        pl: 'Łowca skarbów',
                    },
                    description: {
                        ru: 'Найдите {{target}} сокровищ на работе кладоискателя.',
                        ua: 'Знайдіть {{target}} скарбів на роботі шукача скарбів.',
                        en: 'Find {{target}} treasures while working as a treasure hunter.',
                        de: 'Finde {{target}} Schätze als Schatzsucher.',
                        pl: 'Znajdź {{target}} skarbów pracując jako poszukiwacz skarbów.',
                    },
                },
                miner: {
                    title: {
                        ru: 'Шахтёрский труд',
                        ua: 'Шахтарська праця',
                        en: 'Miner’s labor',
                        de: 'Bergmannsarbeit',
                        pl: 'Praca górnika',
                    },
                    description: {
                        ru: 'Добудьте {{target}} руды на работе шахтёра в карьере.',
                        ua: 'Видобудьте {{target}} руди на роботі шахтаря в кар’єрі.',
                        en: 'Mine {{target}} ore while working as a quarry miner.',
                        de: 'Baue {{target}} Erz als Steinbruch-Bergmann ab.',
                        pl: 'Wydobądź {{target}} rudy pracując jako górnik w kamieniołomie.',
                    },
                },
                garbageBag: {
                    title: {
                        ru: 'Чистый город',
                        ua: 'Чисте місто',
                        en: 'Clean city',
                        de: 'Saubere Stadt',
                        pl: 'Czyste miasto',
                    },
                    description: {
                        ru: 'Соберите {{target}} мешков мусора на работе мусорщика.',
                        ua: 'Зберіть {{target}} мішків сміття на роботі сміттяра.',
                        en: 'Collect {{target}} garbage bags while working as a garbageman.',
                        de: 'Sammle {{target}} Müllsäcke als Müllmann.',
                        pl: 'Zbierz {{target}} worków śmieci pracując jako śmieciarz.',
                    },
                },
            },
            earn: {
                trucker: {
                    title: {
                        ru: 'Большая доставка',
                        ua: 'Велика доставка',
                        en: 'Big haul',
                        de: 'Große Lieferung',
                        pl: 'Wielka dostawa',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ на работе дальнобойщика.',
                        ua: 'Заробіть {{target}}$ на роботі далекобійника.',
                        en: 'Earn {{target}}$ working as a trucker.',
                        de: 'Verdiene {{target}}$ als Fernfahrer.',
                        pl: 'Zarób {{target}}$ pracując jako kierowca ciężarówki.',
                    },
                },
                busman: {
                    title: {
                        ru: 'За рулём автобуса',
                        ua: 'За кермом автобуса',
                        en: 'Behind the bus wheel',
                        de: 'Am Steuer des Busses',
                        pl: 'Za kierownicą autobusu',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ водителем автобуса.',
                        ua: 'Заробіть {{target}}$ водієм автобуса.',
                        en: 'Earn {{target}}$ as a bus driver.',
                        de: 'Verdiene {{target}}$ als Busfahrer.',
                        pl: 'Zarób {{target}}$ jako kierowca autobusu.',
                    },
                },
                taxi: {
                    title: {
                        ru: 'Таксист',
                        ua: 'Таксист',
                        en: 'Cabbie',
                        de: 'Taxifahrer',
                        pl: 'Taksówkarz',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ на работе таксистом.',
                        ua: 'Заробіть {{target}}$ на роботі таксистом.',
                        en: 'Earn {{target}}$ working as a taxi driver.',
                        de: 'Verdiene {{target}}$ als Taxifahrer.',
                        pl: 'Zarób {{target}}$ pracując jako taksówkarz.',
                    },
                },
                garbage: {
                    title: {
                        ru: 'Мусорщик',
                        ua: 'Сміттяр',
                        en: 'Garbageman',
                        de: 'Müllmann',
                        pl: 'Śmieciarz',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ на работе мусорщиком.',
                        ua: 'Заробіть {{target}}$ на роботі сміттяра.',
                        en: 'Earn {{target}}$ working as a garbageman.',
                        de: 'Verdiene {{target}}$ als Müllmann.',
                        pl: 'Zarób {{target}}$ pracując jako śmieciarz.',
                    },
                },
                quarryDumper: {
                    title: {
                        ru: 'Карьерный самосвал',
                        ua: 'Кар’єрний самоскид',
                        en: 'Quarry dumper',
                        de: 'Steinbruch-Kipper',
                        pl: 'Wywrotka w kamieniołomie',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ на самосвале в карьере.',
                        ua: 'Заробіть {{target}}$ на самоскиді в кар’єрі.',
                        en: 'Earn {{target}}$ driving a dumper at the quarry.',
                        de: 'Verdiene {{target}}$ am Kipper im Steinbruch.',
                        pl: 'Zarób {{target}}$ prowadząc wywrotkę w kamieniołomie.',
                    },
                },
                quarryBulldozer: {
                    title: {
                        ru: 'Карьерный бульдозер',
                        ua: 'Кар’єрний бульдозер',
                        en: 'Quarry bulldozer',
                        de: 'Steinbruch-Bulldozer',
                        pl: 'Spychacz w kamieniołomie',
                    },
                    description: {
                        ru: 'Заработайте {{target}}$ на бульдозере в карьере.',
                        ua: 'Заробіть {{target}}$ на бульдозері в кар’єрі.',
                        en: 'Earn {{target}}$ driving a bulldozer at the quarry.',
                        de: 'Verdiene {{target}}$ am Bulldozer im Steinbruch.',
                        pl: 'Zarób {{target}}$ prowadząc spychacz w kamieniołomie.',
                    },
                },
            },
            buyer: {
                diving: {
                    title: {
                        ru: 'Скупщик морской добычи',
                        ua: 'Скупник морської здобичі',
                        en: 'Diving loot buyer',
                        de: 'Tauchbeute-Käufer',
                        pl: 'Skup łupów z nurkowania',
                    },
                    description: {
                        ru: 'Продайте скупщику морской добычи на сумму {{target}}$.',
                        ua: 'Продайте скупнику морської здобичі на суму {{target}}$.',
                        en: 'Sell {{target}}$ worth of diving loot to the buyer.',
                        de: 'Verkaufe Tauchbeute im Wert von {{target}}$ an den Händler.',
                        pl: 'Sprzedaj skupującemu łupy z nurkowania na kwotę {{target}}$.',
                    },
                },
                miner: {
                    title: {
                        ru: 'Скупщик руды',
                        ua: 'Скупник руди',
                        en: 'Ore buyer',
                        de: 'Erz-Käufer',
                        pl: 'Skup rudy',
                    },
                    description: {
                        ru: 'Продайте скупщику руды на сумму {{target}}$.',
                        ua: 'Продайте скупнику руди на суму {{target}}$.',
                        en: 'Sell {{target}}$ worth of ore to the buyer.',
                        de: 'Verkaufe Erz im Wert von {{target}}$ an den Händler.',
                        pl: 'Sprzedaj skupującemu rudę na kwotę {{target}}$.',
                    },
                },
                fishing: {
                    title: {
                        ru: 'Скупщик рыбы',
                        ua: 'Скупник риби',
                        en: 'Fish buyer',
                        de: 'Fisch-Käufer',
                        pl: 'Skup ryb',
                    },
                    description: {
                        ru: 'Продайте скупщику рыбы на сумму {{target}}$.',
                        ua: 'Продайте скупнику риби на суму {{target}}$.',
                        en: 'Sell {{target}}$ worth of fish to the buyer.',
                        de: 'Verkaufe Fisch im Wert von {{target}}$ an den Händler.',
                        pl: 'Sprzedaj skupującemu ryby na kwotę {{target}}$.',
                    },
                },
                hunting: {
                    title: {
                        ru: 'Скупщик мяса',
                        ua: 'Скупник м’яса',
                        en: 'Meat buyer',
                        de: 'Fleisch-Käufer',
                        pl: 'Skup mięsa',
                    },
                    description: {
                        ru: 'Продайте скупщику мяса на сумму {{target}}$.',
                        ua: 'Продайте скупнику м’яса на суму {{target}}$.',
                        en: 'Sell {{target}}$ worth of meat to the buyer.',
                        de: 'Verkaufe Fleisch im Wert von {{target}}$ an den Händler.',
                        pl: 'Sprzedaj skupującemu mięso na kwotę {{target}}$.',
                    },
                },
                farm: {
                    title: {
                        ru: 'Скупщик с фермы',
                        ua: 'Скупник з ферми',
                        en: 'Farm buyer',
                        de: 'Farm-Käufer',
                        pl: 'Skup farmerski',
                    },
                    description: {
                        ru: 'Продайте скупщику фермерских товаров на сумму {{target}}$.',
                        ua: 'Продайте скупнику фермерських товарів на суму {{target}}$.',
                        en: 'Sell {{target}}$ worth of farm goods to the buyer.',
                        de: 'Verkaufe Farm-Waren im Wert von {{target}}$ an den Händler.',
                        pl: 'Sprzedaj skupującemu produkty farmerskie na kwotę {{target}}$.',
                    },
                },
            },
            fishing: {
                any: {
                    title: {
                        ru: 'На рыбалке',
                        ua: 'На риболовлі',
                        en: 'Gone fishing',
                        de: 'Beim Angeln',
                        pl: 'Na rybach',
                    },
                    description: {
                        ru: 'Поймайте {{target}} рыб любого вида.',
                        ua: 'Зловіть {{target}} риб будь-якого виду.',
                        en: 'Catch {{target}} fish of any kind.',
                        de: 'Fange {{target}} beliebige Fische.',
                        pl: 'Złów {{target}} ryb dowolnego gatunku.',
                    },
                },
            },
            inventory: {
                vodka: {
                    title: {
                        ru: 'Душа просит',
                        ua: 'Душа просить',
                        en: 'A shot of courage',
                        de: 'Ein Schluck Mut',
                        pl: 'Po kieliszku',
                    },
                    description: {
                        ru: 'Выпейте водки {{target}} раз.',
                        ua: 'Випийте горілки {{target}} разів.',
                        en: 'Drink vodka {{target}} times.',
                        de: 'Trinke {{target}}-mal Wodka.',
                        pl: 'Wypij wódkę {{target}} razy.',
                    },
                },
                whiskey: {
                    title: {
                        ru: 'Виски-вечер',
                        ua: 'Віскі-вечір',
                        en: 'Whiskey night',
                        de: 'Whiskey-Abend',
                        pl: 'Wieczór z whiskey',
                    },
                    description: {
                        ru: 'Выпейте виски {{target}} раз.',
                        ua: 'Випийте віскі {{target}} разів.',
                        en: 'Drink whiskey {{target}} times.',
                        de: 'Trinke {{target}}-mal Whiskey.',
                        pl: 'Wypij whiskey {{target}} razy.',
                    },
                },
                burger: {
                    title: {
                        ru: 'Любитель бургеров',
                        ua: 'Любитель бургерів',
                        en: 'Burger lover',
                        de: 'Burger-Liebhaber',
                        pl: 'Miłośnik burgerów',
                    },
                    description: {
                        ru: 'Съешьте бургер {{target}} раз.',
                        ua: 'З’їжте бургер {{target}} разів.',
                        en: 'Eat a burger {{target}} times.',
                        de: 'Iss {{target}}-mal einen Burger.',
                        pl: 'Zjedz burgera {{target}} razy.',
                    },
                },
            },
            money: {
                transfer: {
                    title: {
                        ru: 'Помощь товарищу',
                        ua: 'Допомога товаришу',
                        en: 'Lend a hand',
                        de: 'Hilf einem Freund',
                        pl: 'Pomoc koledze',
                    },
                    description: {
                        ru: 'Совершите {{target}} денежных переводов другим игрокам.',
                        ua: 'Здійсніть {{target}} грошових переказів іншим гравцям.',
                        en: 'Make {{target}} money transfers to other players.',
                        de: 'Tätige {{target}} Geldüberweisungen an andere Spieler.',
                        pl: 'Wykonaj {{target}} przelewów pieniężnych do innych graczy.',
                    },
                },
            },
            shopping: {
                any: {
                    title: {
                        ru: 'Шопинг',
                        ua: 'Шопінг',
                        en: 'Shopping spree',
                        de: 'Shoppingtour',
                        pl: 'Zakupy',
                    },
                    description: {
                        ru: 'Совершите покупку в любом магазине.',
                        ua: 'Зробіть покупку в будь-якому магазині.',
                        en: 'Make a purchase in any store.',
                        de: 'Kaufe etwas in einem beliebigen Laden.',
                        pl: 'Dokonaj zakupu w dowolnym sklepie.',
                    },
                },
            },
            vehicle: {
                spawn: {
                    title: {
                        ru: 'Колёсный мастер',
                        ua: 'Майстер кермa',
                        en: 'Wheel master',
                        de: 'Lenkrad-Meister',
                        pl: 'Mistrz kierownicy',
                    },
                    description: {
                        ru: 'Заспавните личный транспорт {{target}} раз.',
                        ua: 'Виклич особистий транспорт {{target}} разів.',
                        en: 'Spawn your personal vehicle {{target}} times.',
                        de: 'Rufe dein persönliches Fahrzeug {{target}}-mal.',
                        pl: 'Wezwij swój pojazd osobisty {{target}} razy.',
                    },
                },
            },
            casino: {
                luckyWheel: {
                    title: {
                        ru: 'Колесо фортуны',
                        ua: 'Колесо фортуни',
                        en: 'Wheel of fortune',
                        de: 'Glücksrad',
                        pl: 'Koło fortuny',
                    },
                    description: {
                        ru: 'Покрутите колесо фортуны в казино.',
                        ua: 'Покрутіть колесо фортуни в казино.',
                        en: 'Spin the wheel of fortune at the casino.',
                        de: 'Drehe das Glücksrad im Casino.',
                        pl: 'Zakręć kołem fortuny w kasynie.',
                    },
                },
                roulette: {
                    title: {
                        ru: 'Игрок в рулетку',
                        ua: 'Гравець у рулетку',
                        en: 'Roulette player',
                        de: 'Roulette-Spieler',
                        pl: 'Gracz ruletki',
                    },
                    description: {
                        ru: 'Сделайте ставок в рулетке на сумму {{target}} фишек.',
                        ua: 'Зробіть ставок у рулетці на суму {{target}} фішок.',
                        en: 'Place {{target}} chips worth of bets at the roulette.',
                        de: 'Setze Roulette-Einsätze im Wert von {{target}} Chips.',
                        pl: 'Postaw zakłady w ruletce na kwotę {{target}} żetonów.',
                    },
                },
            },
            phone: {
                sms: {
                    title: {
                        ru: 'Мастер переписки',
                        ua: 'Майстер листування',
                        en: 'Texting pro',
                        de: 'SMS-Profi',
                        pl: 'Mistrz SMS-ów',
                    },
                    description: {
                        ru: 'Отправьте {{target}} SMS-сообщений.',
                        ua: 'Надішліть {{target}} SMS-повідомлень.',
                        en: 'Send {{target}} text messages.',
                        de: 'Sende {{target}} SMS-Nachrichten.',
                        pl: 'Wyślij {{target}} wiadomości SMS.',
                    },
                },
                call: {
                    title: {
                        ru: 'Долгие разговоры',
                        ua: 'Довгі розмови',
                        en: 'Long talks',
                        de: 'Lange Gespräche',
                        pl: 'Długie rozmowy',
                    },
                    description: {
                        ru: 'Завершите {{target}} телефонных звонков.',
                        ua: 'Завершіть {{target}} телефонних дзвінків.',
                        en: 'Finish {{target}} phone calls.',
                        de: 'Beende {{target}} Telefongespräche.',
                        pl: 'Zakończ {{target}} rozmów telefonicznych.',
                    },
                },
                flappyBird: {
                    title: {
                        ru: 'Рекорд в Flappy Bird',
                        ua: 'Рекорд у Flappy Bird',
                        en: 'Flappy Bird record',
                        de: 'Flappy-Bird-Rekord',
                        pl: 'Rekord we Flappy Bird',
                    },
                    description: {
                        ru: 'Установите новый рекорд в Flappy Bird.',
                        ua: 'Встановіть новий рекорд у Flappy Bird.',
                        en: 'Set a new record in Flappy Bird.',
                        de: 'Stelle einen neuen Rekord in Flappy Bird auf.',
                        pl: 'Ustanów nowy rekord we Flappy Bird.',
                    },
                },
            },
            service: {
                repair: {
                    title: {
                        ru: 'Автомеханик',
                        ua: 'Автомеханік',
                        en: 'Auto mechanic',
                        de: 'Automechaniker',
                        pl: 'Mechanik samochodowy',
                    },
                    description: {
                        ru: 'Отремонтируйте транспорт {{target}} раз.',
                        ua: 'Полагодьте транспорт {{target}} разів.',
                        en: 'Repair vehicles {{target}} times.',
                        de: 'Repariere {{target}}-mal Fahrzeuge.',
                        pl: 'Napraw pojazdy {{target}} razy.',
                    },
                },
            },
            medical: {
                checkup: {
                    title: {
                        ru: 'Медосмотр',
                        ua: 'Медогляд',
                        en: 'Medical checkup',
                        de: 'Vorsorgeuntersuchung',
                        pl: 'Badanie lekarskie',
                    },
                    description: {
                        ru: 'Пройдите медосмотр у врача.',
                        ua: 'Пройдіть медогляд у лікаря.',
                        en: 'Get a medical checkup from a doctor.',
                        de: 'Lass dich beim Arzt untersuchen.',
                        pl: 'Zrób badanie lekarskie u lekarza.',
                    },
                },
                takeBlood: {
                    title: {
                        ru: 'Сдать кровь',
                        ua: 'Здати кров',
                        en: 'Donate blood',
                        de: 'Blut spenden',
                        pl: 'Oddaj krew',
                    },
                    description: {
                        ru: 'Сдайте кровь у врача.',
                        ua: 'Здайте кров у лікаря.',
                        en: 'Donate blood at the doctor’s.',
                        de: 'Spende Blut beim Arzt.',
                        pl: 'Oddaj krew u lekarza.',
                    },
                },
            },
        },
        rating: {
            tabName: {
                ru: 'Рейтинг',
                ua: 'Рейтинг',
                en: 'Rating',
                de: 'Wertung',
                pl: 'Ranking',
            },
            title: {
                ru: 'Рейтинг сезона',
                ua: 'Рейтинг сезону',
                en: 'Season rating',
                de: 'Saisonwertung',
                pl: 'Ranking sezonu',
            },
            description: {
                ru: 'Соревнуйтесь с другими игроками за лучшие места в общем рейтинге пропуска сезона.',
                ua: 'Змагайтеся з іншими гравцями за найкращі місця у загальному рейтингу пропуску сезону.',
                en: 'Compete with other players for top spots in the overall season pass leaderboard.',
                de: 'Tritt gegen andere Spieler in der Gesamtrangliste des Saisonpasses an.',
                pl: 'Rywalizuj z innymi graczami o najwyższe miejsca w ogólnym rankingu przepustki sezonu.',
            },
        },
    },
    tiers: {
        none: {
            ru: 'Нет пропуска',
            ua: 'Немає пропуску',
            en: 'No pass',
            de: 'Kein Pass',
            pl: 'Brak przepustki',
        },
        free: {
            ru: 'Базовый',
            ua: 'Базовий',
            en: 'Free',
            de: 'Kostenlos',
            pl: 'Darmowy',
        },
        starter: {
            ru: 'Стартовый',
            ua: 'Стартовий',
            en: 'Starter',
            de: 'Starter',
            pl: 'Startowy',
        },
        bronze: {
            ru: 'Бронзовый',
            ua: 'Бронзовий',
            en: 'Bronze',
            de: 'Bronze',
            pl: 'Brązowy',
        },
        silver: {
            ru: 'Серебряный',
            ua: 'Срібний',
            en: 'Silver',
            de: 'Silber',
            pl: 'Srebrny',
        },
        gold: {
            ru: 'Золотой',
            ua: 'Золотий',
            en: 'Gold',
            de: 'Gold',
            pl: 'Złoty',
        },
    },
    sidebar: {
        upgrade: {
            ru: 'Улучшить',
            ua: 'Покращити',
            en: 'Upgrade',
            de: 'Verbessern',
            pl: 'Ulepsz',
        },
        upgradePass: {
            ru: 'Улучшить пропуск',
            ua: 'Покращити пропуск',
            en: 'Upgrade pass',
            de: 'Pass verbessern',
            pl: 'Ulepsz przepustkę',
        },
        xpToNext: {
            ru: 'Опыта для повышения уровня',
            ua: 'Досвіду для підвищення рівня',
            en: 'XP to next level',
            de: 'XP bis zum nächsten Level',
            pl: 'XP do następnego poziomu',
        },
        premiumLevels: {
            ru: 'Премиум уровни',
            ua: 'Преміум рівні',
            en: 'Premium levels',
            de: 'Premium-Level',
            pl: 'Poziomy premium',
        },
    },
    lines: {
        free: {
            ru: 'Обычный',
            ua: 'Звичайний',
            en: 'Regular',
            de: 'Normal',
            pl: 'Zwykły',
        },
        premium: {
            ru: 'Премиум',
            ua: 'Преміум',
            en: 'Premium',
            de: 'Premium',
            pl: 'Premium',
        },
    },
    controls: {
        myLevel: {
            ru: 'Мой уровень',
            ua: 'Мій рівень',
            en: 'My level',
            de: 'Mein Level',
            pl: 'Mój poziom',
        },
    },
    progressBar: {
        purchaseLevel: {
            ru: 'Купить {{level}} уровень',
            ua: 'Купити {{level}} рівень',
            en: 'Buy level {{level}}',
            de: 'Level {{level}} kaufen',
            pl: 'Kup poziom {{level}}',
        },
    },
    timer: {
        endsIn: {
            ru: 'Событие завершается через',
            ua: 'Подія завершується через',
            en: 'Event ends in',
            de: 'Event endet in',
            pl: 'Wydarzenie kończy się za',
        },
        daysWord: {
            ru: 'дней',
            ua: 'днів',
            en: 'days',
            de: 'Tage',
            pl: 'dni',
        },
    },
    notify: {
        tierUpgradeTitle: {
            ru: 'Боевой пропуск',
            ua: 'Бойовий пропуск',
            en: 'Battle Pass',
            de: 'Battle Pass',
            pl: 'Karnet bojowy',
        },
        tierUpgradeBody: {
            ru: 'Активирован тир «{{tier}}»',
            ua: 'Активовано тир «{{tier}}»',
            en: 'Tier "{{tier}}" activated',
            de: 'Stufe „{{tier}}" aktiviert',
            pl: 'Aktywowano poziom „{{tier}}"',
        },
        tierUpgradeNoFunds: {
            ru: 'Недостаточно Olymp-Coin для покупки этого тира',
            ua: 'Недостатньо Olymp-Coin для покупки цього тиру',
            en: 'Not enough Olymp-Coin to buy this tier',
            de: 'Nicht genug Olymp-Coin für diese Stufe',
            pl: 'Za mało Olymp-Coin, aby kupić ten poziom',
        },
        freeXpClaimed: {
            ru: 'Получено {{xp}} опыта пропуска',
            ua: 'Отримано {{xp}} досвіду пропуску',
            en: 'Received {{xp}} pass XP',
            de: '{{xp}} Pass-XP erhalten',
            pl: 'Otrzymano {{xp}} XP przepustki',
        },
        buyXpDone: {
            ru: 'Куплено {{xp}} опыта за {{price}} Olymp-Coin',
            ua: 'Куплено {{xp}} досвіду за {{price}} Olymp-Coin',
            en: 'Bought {{xp}} XP for {{price}} Olymp-Coin',
            de: '{{xp}} XP für {{price}} Olymp-Coin gekauft',
            pl: 'Kupiono {{xp}} XP za {{price}} Olymp-Coin',
        },
        warehouseAdded: {
            ru: 'Награда отправлена в донат-инвентарь',
            ua: 'Нагороду надіслано в донат-інвентар',
            en: 'Reward sent to donate inventory',
            de: 'Belohnung ins Donate-Inventar gesendet',
            pl: 'Nagrodę wysłano do inwentarza donate',
        },
        sellDone: {
            ru: 'Награда продана за {{price}} Olymp-Coin',
            ua: 'Нагороду продано за {{price}} Olymp-Coin',
            en: 'Reward sold for {{price}} Olymp-Coin',
            de: 'Belohnung für {{price}} Olymp-Coin verkauft',
            pl: 'Nagroda sprzedana za {{price}} Olymp-Coin',
        },
        sellForXpDone: {
            ru: 'Награда обменяна на {{xp}} опыта пропуска',
            ua: 'Нагороду обміняно на {{xp}} досвіду пропуску',
            en: 'Reward exchanged for {{xp}} pass XP',
            de: 'Belohnung gegen {{xp}} Pass-XP getauscht',
            pl: 'Nagrodę wymieniono na {{xp}} XP przepustki',
        },
        seasonRewardsTransferred: {
            ru: 'Награды прошлого сезона перенесены в донат-инвентарь ({{count}} шт.)',
            ua: 'Нагороди минулого сезону перенесено в донат-інвентар ({{count}} шт.)',
            en: 'Last season rewards moved to donate inventory ({{count}} items)',
            de: 'Belohnungen der letzten Saison wurden ins Donate-Inventar verschoben ({{count}} Stk.)',
            pl: 'Nagrody z poprzedniego sezonu przeniesiono do inwentarza donate ({{count}} szt.)',
        },
        taskCompleted: {
            ru: 'Задание «{{title}}» выполнено',
            ua: 'Завдання «{{title}}» виконано',
            en: 'Task "{{title}}" completed',
            de: 'Aufgabe „{{title}}" abgeschlossen',
            pl: 'Zadanie „{{title}}" ukończone',
        },
        tasksRefreshDone: {
            ru: 'Список заданий обновлён',
            ua: 'Список завдань оновлено',
            en: 'Tasks list refreshed',
            de: 'Aufgabenliste aktualisiert',
            pl: 'Lista zadań odświeżona',
        },
        tasksRefreshNoFunds: {
            ru: 'Недостаточно Olymp-Coin для обновления заданий',
            ua: 'Недостатньо Olymp-Coin для оновлення завдань',
            en: 'Not enough Olymp-Coin to refresh tasks',
            de: 'Nicht genug Olymp-Coin zum Aktualisieren der Aufgaben',
            pl: 'Za mało Olymp-Coin, aby odświeżyć zadania',
        },
        actionFailedNoTier: {
            ru: 'У вас не активирован боевой пропуск',
            ua: 'У вас не активовано бойовий пропуск',
            en: "You don't have an active Battle Pass",
            de: 'Du hast keinen aktiven Battle Pass',
            pl: 'Nie masz aktywnego karnetu bojowego',
        },
        actionFailedLocked: {
            ru: 'Уровень ещё не открыт',
            ua: 'Рівень ще не відкрито',
            en: 'Level not yet unlocked',
            de: 'Stufe noch nicht freigeschaltet',
            pl: 'Poziom jeszcze nie odblokowany',
        },
        actionFailedAlreadyClaimed: {
            ru: 'Эта награда уже получена',
            ua: 'Цю нагороду вже отримано',
            en: 'This reward has already been claimed',
            de: 'Diese Belohnung wurde bereits eingelöst',
            pl: 'Ta nagroda została już odebrana',
        },
        sellForXpFailedNoPrice: {
            ru: 'Эту награду нельзя обменять на опыт',
            ua: 'Цю нагороду не можна обміняти на досвід',
            en: "This reward can't be exchanged for XP",
            de: 'Diese Belohnung kann nicht gegen XP getauscht werden',
            pl: 'Tej nagrody nie można wymienić na XP',
        },
        sellFailedNotSellable: {
            ru: 'Эту награду нельзя продать',
            ua: 'Цю нагороду не можна продати',
            en: "This reward can't be sold",
            de: 'Diese Belohnung kann nicht verkauft werden',
            pl: 'Tej nagrody nie można sprzedać',
        },
        claimFailed: {
            ru: 'Не удалось забрать награду',
            ua: 'Не вдалося забрати нагороду',
            en: 'Failed to claim reward',
            de: 'Belohnung konnte nicht eingelöst werden',
            pl: 'Nie udało się odebrać nagrody',
        },
        sellFailed: {
            ru: 'Не удалось продать награду',
            ua: 'Не вдалося продати нагороду',
            en: 'Failed to sell reward',
            de: 'Belohnung konnte nicht verkauft werden',
            pl: 'Nie udało się sprzedać nagrody',
        },
        sellXpFailed: {
            ru: 'Не удалось обменять награду на опыт',
            ua: 'Не вдалося обміняти нагороду на досвід',
            en: 'Failed to exchange reward for XP',
            de: 'Belohnung konnte nicht gegen XP getauscht werden',
            pl: 'Nie udało się wymienić nagrody na XP',
        },
        warehouseFailed: {
            ru: 'Не удалось отправить награду на склад',
            ua: 'Не вдалося надіслати нагороду на склад',
            en: 'Failed to send reward to warehouse',
            de: 'Belohnung konnte nicht ins Lager gesendet werden',
            pl: 'Nie udało się wysłać nagrody do magazynu',
        },
        cardRandomFailed: {
            ru: 'Не удалось забрать приз карточной игры',
            ua: 'Не вдалося забрати приз карткової гри',
            en: 'Failed to claim card game prize',
            de: 'Kartenspiel-Belohnung konnte nicht eingelöst werden',
            pl: 'Nie udało się odebrać nagrody z gry kart',
        },
        actionFailedMaxLevel: {
            ru: 'Достигнут максимальный уровень пропуска',
            ua: 'Досягнуто максимальний рівень пропуску',
            en: 'Battle Pass max level already reached',
            de: 'Maximale Battle-Pass-Stufe bereits erreicht',
            pl: 'Osiągnięto maksymalny poziom karnetu',
        },
        actionFailedAlreadyReached: {
            ru: 'Этот уровень уже достигнут',
            ua: 'Цей рівень вже досягнуто',
            en: 'This level is already reached',
            de: 'Diese Stufe wurde bereits erreicht',
            pl: 'Ten poziom został już osiągnięty',
        },
        actionFailedInvalidOffer: {
            ru: 'Это предложение недоступно',
            ua: 'Ця пропозиція недоступна',
            en: 'This offer is unavailable',
            de: 'Dieses Angebot ist nicht verfügbar',
            pl: 'Ta oferta jest niedostępna',
        },
        actionFailedInvalidLevel: {
            ru: 'Указан некорректный уровень',
            ua: 'Вказано некоректний рівень',
            en: 'Invalid target level',
            de: 'Ungültige Ziel-Stufe',
            pl: 'Nieprawidłowy poziom docelowy',
        },
    },
    freeXp: {
        title: {
            ru: '{{hours}} часов игры = {{xp}} опыта',
            ua: '{{hours}} годин гри = {{xp}} досвіду',
            en: '{{hours}} hours played = {{xp}} XP',
            de: '{{hours}} Stunden Spielzeit = {{xp}} XP',
            pl: '{{hours}} godzin gry = {{xp}} XP',
        },
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        claimableIn: {
            ru: 'Можно забрать через',
            ua: 'Можна забрати через',
            en: 'Available in',
            de: 'Verfügbar in',
            pl: 'Dostępne za',
        },
    },
    rewards: {
        claim: {
            ru: 'Забрать',
            ua: 'Забрати',
            en: 'Claim',
            de: 'Abholen',
            pl: 'Odbierz',
        },
        sell: {
            ru: 'Продать',
            ua: 'Продати',
            en: 'Sell',
            de: 'Verkaufen',
            pl: 'Sprzedaj',
        },
        warehouse: {
            ru: 'На склад',
            ua: 'На склад',
            en: 'To warehouse',
            de: 'Ins Lager',
            pl: 'Do magazynu',
        },
        qtyShort: {
            ru: 'шт.',
            ua: 'шт.',
            en: 'pcs',
            de: 'St.',
            pl: 'szt.',
        },
        days: {
            ru: 'д.',
            ua: 'д.',
            en: 'd',
            de: 'T.',
            pl: 'd.',
        },
        claimSelf: {
            ru: 'Забрать себе',
            ua: 'Забрати собі',
            en: 'Claim for yourself',
            de: 'Für sich nehmen',
            pl: 'Weź dla siebie',
        },
        breakdown: {
            ru: 'Разобрать на',
            ua: 'Розібрати на',
            en: 'Disassemble for',
            de: 'Zerlegen für',
            pl: 'Rozłóż na',
        },
        toDonateInventory: {
            ru: 'Отложить в донат инвентарь',
            ua: 'Відкласти в донат інвентар',
            en: 'Save to donate inventory',
            de: 'In Donate-Inventar legen',
            pl: 'Odłóż do inwentarza donate',
        },
        sellForXp: {
            ru: 'Продать за',
            ua: 'Продати за',
            en: 'Sell for',
            de: 'Verkaufen für',
            pl: 'Sprzedaj za',
        },
    },
    categories: {
        default: {
            ru: 'Награда',
            ua: 'Нагорода',
            en: 'Reward',
            de: 'Belohnung',
            pl: 'Nagroda',
        },
        currency: {
            ru: 'Деньги',
            ua: 'Гроші',
            en: 'Cash',
            de: 'Geld',
            pl: 'Pieniądze',
        },
        donate: {
            ru: 'Монеты',
            ua: 'Монети',
            en: 'Coins',
            de: 'Münzen',
            pl: 'Monety',
        },
        experience: {
            ru: 'Опыт',
            ua: 'Досвід',
            en: 'Experience',
            de: 'Erfahrung',
            pl: 'Doświadczenie',
        },
        cases: {
            ru: 'Кейс',
            ua: 'Кейс',
            en: 'Case',
            de: 'Kiste',
            pl: 'Skrzynka',
        },
        vehicles: {
            ru: 'Транспорт',
            ua: 'Транспорт',
            en: 'Vehicle',
            de: 'Fahrzeug',
            pl: 'Pojazd',
        },
        skins: {
            ru: 'Скин',
            ua: 'Скін',
            en: 'Skin',
            de: 'Skin',
            pl: 'Skórka',
        },
        statuses: {
            ru: 'Статус',
            ua: 'Статус',
            en: 'Status',
            de: 'Status',
            pl: 'Status',
        },
        animations: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
        features: {
            ru: 'Особенность',
            ua: 'Особливість',
            en: 'Feature',
            de: 'Funktion',
            pl: 'Funkcja',
        },
        weapon: {
            ru: 'Оружие',
            ua: 'Зброя',
            en: 'Weapon',
            de: 'Waffe',
            pl: 'Broń',
        },
        ammo: {
            ru: 'Патроны',
            ua: 'Патрони',
            en: 'Ammo',
            de: 'Munition',
            pl: 'Amunicja',
        },
        clothes: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        backpack: {
            ru: 'Одежда',
            ua: 'Одяг',
            en: 'Clothing',
            de: 'Kleidung',
            pl: 'Odzież',
        },
        blueprint: {
            ru: 'Чертёж',
            ua: 'Креслення',
            en: 'Blueprint',
            de: 'Bauplan',
            pl: 'Schemat',
        },
        item: {
            ru: 'Предмет',
            ua: 'Предмет',
            en: 'Item',
            de: 'Gegenstand',
            pl: 'Przedmiot',
        },
    },
    featured: {
        title: {
            ru: 'Главные призы',
            ua: 'Головні призи',
            en: 'Featured prizes',
            de: 'Hauptpreise',
            pl: 'Główne nagrody',
        },
    },
    seasons: {
        summer: {
            name: {
                ru: 'Боевой пропуск',
                ua: 'Бойовий пропуск',
                en: 'Battle Pass',
                de: 'Battle Pass',
                pl: 'Karnet bojowy',
            },
            description: {
                ru: 'Открывайте уникальные награды за прохождение уровней. Выполняйте задания и получайте опыт.',
                ua: 'Відкривайте унікальні нагороди за проходження рівнів. Виконуйте завдання та отримуйте досвід.',
                en: 'Unlock unique rewards as you level up. Complete tasks and gain experience.',
                de: 'Schalte einzigartige Belohnungen frei, indem du Level aufsteigst. Erfülle Aufgaben und sammle Erfahrung.',
                pl: 'Odblokowuj unikalne nagrody, awansując na kolejne poziomy. Wykonuj zadania i zdobywaj doświadczenie.',
            },
        },
    },
    rewardNames: {
        animation: {
            ru: 'Анимация',
            ua: 'Анімація',
            en: 'Animation',
            de: 'Animation',
            pl: 'Animacja',
        },
    },
    placeholder: {
        wip: {
            ru: 'В разработке',
            ua: 'В розробці',
            en: 'Work in progress',
            de: 'In Bearbeitung',
            pl: 'W trakcie prac',
        },
    },
};
