export default {
    enter: {
        ru: 'Чтобы начать игру в теннис, нажмите',
        ua: 'Щоб почати гру в теніс, натисніть',
        en: 'To start a tennis match, press',
        de: 'Drücke, um ein Tennisspiel zu starten',
        pl: 'Aby rozpocząć grę w tenisa, naciśnij',
        zh: '按下开始打网球',
    },
    alreadyPlaying: {
        ru: 'Вы уже играете в теннис.',
        ua: 'Ви вже граєте в теніс.',
        en: 'You are already playing tennis.',
        de: 'Du spielst bereits Tennis.',
        pl: 'Już grasz w tenisa.',
        zh: '你已经在打网球了。',
    },
    positionOccupied: {
        ru: 'Это место уже занято.',
        ua: 'Це місце вже зайняте.',
        en: 'This position is already occupied.',
        de: 'Diese Position ist bereits besetzt.',
        pl: 'To miejsce jest już zajęte.',
        zh: '这个位置已被占用。',
    },
    waitingOpponent: {
        ru: 'Ожидание соперника',
        ua: 'Очікування суперника',
        en: 'Waiting for opponent',
        de: 'Warten auf Gegner',
        pl: 'Oczekiwanie na przeciwnika',
        zh: '等待对手',
    },
    practiceMachine: {
        ru: 'Тренажёр',
        ua: 'Тренажер',
        en: 'Ball machine',
        de: 'Ballmaschine',
        pl: 'Maszyna treningowa',
        zh: '发球机',
    },
    scoreOpponent: {
        ru: 'Соперник',
        ua: 'Суперник',
        en: 'Opponent',
        de: 'Gegner',
        pl: 'Przeciwnik',
        zh: '对手',
    },
    scoreYou: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },
    scoreboardTitle: {
        ru: 'Теннис',
        ua: 'Теніс',
        en: 'Tennis',
        de: 'Tennis',
        pl: 'Tenis',
        zh: '网球',
    },
    scoreboardColumn: {
        ru: 'Счёт',
        ua: 'Рахунок',
        en: 'Score',
        de: 'Punktestand',
        pl: 'Wynik',
        zh: '比分',
    },
    scoreboardGames: {
        ru: 'Геймы',
        ua: 'Гейми',
        en: 'Games',
        de: 'Spiele',
        pl: 'Gemy',
        zh: '局',
    },
    scoreboardSets: {
        ru: 'Сеты',
        ua: 'Сети',
        en: 'Sets',
        de: 'Sätze',
        pl: 'Sety',
        zh: '盘',
    },
    scoreboardPoints: {
        ru: 'Поинт',
        ua: 'Поінт',
        en: 'Points',
        de: 'Punkte',
        pl: 'Punkty',
        zh: '分',
    },
    scoreboardDeuceCourt: {
        ru: 'Ровная сторона',
        ua: 'Рівна сторона',
        en: 'Deuce court',
        de: 'Einstandseite',
        pl: 'Strona deuce',
        zh: '平分区',
    },
    scoreboardAdCourt: {
        ru: 'Сторона больше',
        ua: 'Сторона переваги',
        en: 'Ad court',
        de: 'Vorteilsseite',
        pl: 'Strona przewagi',
        zh: '占先区',
    },
    scoreboardSecondServe: {
        ru: 'Вторая подача',
        ua: 'Друга подача',
        en: 'Second serve',
        de: 'Zweiter Aufschlag',
        pl: 'Drugi serwis',
        zh: '二发',
    },
    serveAim: {
        ru: 'Подача: ЛКМ начать, A / D сместиться',
        ua: 'Подача: ЛКМ почати, A / D зміститися',
        en: 'Serve: LMB to start, A / D to move',
        de: 'Aufschlag: LMT starten, A / D bewegen',
        pl: 'Serwis: LPM rozpocznij, A / D przesuń się',
        zh: '发球：鼠标左键开始，A / D 调整位置',
    },
    serveSwing: {
        ru: 'Подача: ЛКМ зафиксировать силу удара',
        ua: 'Подача: ЛКМ зафіксувати силу удару',
        en: 'Serve: LMB to lock shot power',
        de: 'Aufschlag: LMT, um die Schlagkraft festzulegen',
        pl: 'Serwis: LPM, aby zablokować siłę uderzenia',
        zh: '发球：鼠标左键锁定击球力度',
    },
    rallyControls: {
        ru: 'Удар: ЛКМ обычный, ПКМ топспин, ПРОБЕЛ подрезка',
        ua: 'Удар: ЛКМ звичайний, ПКМ топспін, ПРОБІЛ підрізка',
        en: 'Shot: LMB normal, RMB topspin, SPACE slice',
        de: 'Schlag: LMT normal, RMT Topspin, LEERTASTE Slice',
        pl: 'Uderzenie: LPM zwykłe, PPM topspin, SPACJA slice',
        zh: '击球：左键普通，右键上旋，空格切削',
    },
    uiServeStart: {
        ru: 'Начать подачу',
        ua: 'Почати подачу',
        en: 'Start serve',
        de: 'Aufschlag starten',
        pl: 'Rozpocznij serwis',
        zh: '开始发球',
    },
    uiLockPower: {
        ru: 'Зафиксировать силу',
        ua: 'Зафіксувати силу',
        en: 'Lock power',
        de: 'Kraft festlegen',
        pl: 'Zablokuj siłę',
        zh: '锁定力度',
    },
    uiMoveLeft: {
        ru: 'Сместиться влево',
        ua: 'Зміститися вліво',
        en: 'Move left',
        de: 'Nach links',
        pl: 'Przesuń w lewo',
        zh: '向左移动',
    },
    uiMoveRight: {
        ru: 'Сместиться вправо',
        ua: 'Зміститися вправо',
        en: 'Move right',
        de: 'Nach rechts',
        pl: 'Przesuń w prawo',
        zh: '向右移动',
    },
    uiNormalShot: {
        ru: 'Обычный удар',
        ua: 'Звичайний удар',
        en: 'Normal shot',
        de: 'Normaler Schlag',
        pl: 'Zwykłe uderzenie',
        zh: '普通击球',
    },
    uiTopspinShot: {
        ru: 'Топспин',
        ua: 'Топспін',
        en: 'Topspin',
        de: 'Topspin',
        pl: 'Topspin',
        zh: '上旋',
    },
    uiLobShot: {
        ru: 'Свеча',
        ua: 'Свічка',
        en: 'Lob',
        de: 'Lob',
        pl: 'Lob',
        zh: '吊高球',
    },
    uiSliceShot: {
        ru: 'Подрезка',
        ua: 'Підрізка',
        en: 'Slice',
        de: 'Slice',
        pl: 'Slice',
        zh: '切削',
    },
    shardYou: {
        ru: 'Вы',
        ua: 'Ви',
        en: 'You',
        de: 'Du',
        pl: 'Ty',
        zh: '你',
    },
    shardOpponent: {
        ru: 'Соперник',
        ua: 'Суперник',
        en: 'Opponent',
        de: 'Gegner',
        pl: 'Przeciwnik',
        zh: '对手',
    },
    shard_fault: {
        ru: 'Ошибка подачи',
        ua: 'Помилка подачі',
        en: 'Fault',
        de: 'Aufschlagfehler',
        pl: 'Błąd serwisu',
        zh: '发球失误',
    },
    shard_doubleFault: {
        ru: 'Двойная ошибка',
        ua: 'Подвійна помилка',
        en: 'Double fault',
        de: 'Doppelfehler',
        pl: 'Podwójny błąd',
        zh: '双误',
    },
    shard_secondServe: {
        ru: 'Вторая подача',
        ua: 'Друга подача',
        en: 'Second serve',
        de: 'Zweiter Aufschlag',
        pl: 'Drugi serwis',
        zh: '二发',
    },
    shard_ace: {
        ru: 'Эйс',
        ua: 'Ейс',
        en: 'Ace',
        de: 'Ass',
        pl: 'As',
        zh: '发球直接得分',
    },
    shard_let: {
        ru: 'Переигровка подачи',
        ua: 'Перегравання подачі',
        en: 'Let',
        de: 'Netzaufschlag',
        pl: 'Let',
        zh: '擦网重发',
    },
    shard_deuce: {
        ru: 'Ровно',
        ua: 'Рівно',
        en: 'Deuce',
        de: 'Einstand',
        pl: 'Równowaga',
        zh: '平分',
    },
    shard_advantage: {
        ru: 'Больше',
        ua: 'Перевага',
        en: 'Advantage',
        de: 'Vorteil',
        pl: 'Przewaga',
        zh: '占先',
    },
    shard_gamePoint: {
        ru: 'Геймбол',
        ua: 'Геймбол',
        en: 'Game point',
        de: 'Spielball',
        pl: 'Piłka gemowa',
        zh: '局点',
    },
    shard_breakPoint: {
        ru: 'Брейк-пойнт',
        ua: 'Брейк-пойнт',
        en: 'Break point',
        de: 'Breakball',
        pl: 'Break point',
        zh: '破发点',
    },
    shard_setPoint: {
        ru: 'Сетбол',
        ua: 'Сетбол',
        en: 'Set point',
        de: 'Satzball',
        pl: 'Piłka setowa',
        zh: '盘点',
    },
    shard_matchPoint: {
        ru: 'Матчбол',
        ua: 'Матчбол',
        en: 'Match point',
        de: 'Matchball',
        pl: 'Piłka meczowa',
        zh: '赛点',
    },
    shard_gameWon: {
        ru: 'Гейм',
        ua: 'Гейм',
        en: 'Game won',
        de: 'Spiel gewonnen',
        pl: 'Gem wygrany',
        zh: '赢下此局',
    },
    shard_setWon: {
        ru: 'Сет',
        ua: 'Сет',
        en: 'Set won',
        de: 'Satz gewonnen',
        pl: 'Set wygrany',
        zh: '赢下此盘',
    },
    shard_matchWon: {
        ru: 'Победа',
        ua: 'Перемога',
        en: 'Match won',
        de: 'Match gewonnen',
        pl: 'Mecz wygrany',
        zh: '赢下比赛',
    },
    shard_matchLost: {
        ru: 'Поражение',
        ua: 'Поразка',
        en: 'Match lost',
        de: 'Match verloren',
        pl: 'Mecz przegrany',
        zh: '输掉比赛',
    },
    shard_tiebreak: {
        ru: 'Тай-брейк',
        ua: 'Тай-брейк',
        en: 'Tiebreak',
        de: 'Tie-Break',
        pl: 'Tie-break',
        zh: '抢七',
    },
};
